// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	Email  string  `json:"email"`
	Number float64 `json:"number"`
}

type UserInput struct {
	Email  string  `json:"email"`
	Number float64 `json:"number"`
}
